### ISSUE TITLE
Training doesn't go past 1 epoch

### ISSUE THREAD

**Issue by vj-1988** [titu1994/DenseNet#11]
I am training cifar10 dataset using cifar10.py script. I am able to start the training but the training doesn't go beyond 1 epoch. I am not getting any error messages. I waited for close to one hour for the training to move forward but nothing happens.

Is it because of the different versions of Keras/Theano? I am currently using keras version 2.0.2 and theano 0.9. And I am using TitanX gpu.

**Comment by titu1994** [comment]
DenseNets are extremely deep and wide networks. Even simple ones require a huge compile time when using Theano. I suggest switching to Tensorflow for DenseNets.

**Comment by vj-1988** [comment]
@titu1994 : Thank you. Switching to tensorflow works for me !
