### ISSUE TITLE
Implementation help

### ISSUE THREAD

**Issue by pGit1** [titu1994/DenseNet#13]
@titu1994 ,

Sorry for being a python noob but how does this implementation work? I tested and see that the code works as is to construct the model, but it builds the mode with a call to the DenseNet() function. My question is how does it do this even though the DenseNet function **never** makes a call to the other  DenseNet building blocks functions (the ones prefixed with "__")? This is very confusing to me but amazing at the same time. PLEASE HELP!

**Comment by titu1994** [comment]
See line 108 in densenet.py. It calls the __create_dense_net(...) method, which calls the other __ methods.

**Comment by pGit1** [comment]
This is a great implementation. The best I've seen. Really wish I could spend a weekend learning from you.
