### ISSUE TITLE
Missing last connection on FC-DenseNet?

### ISSUE THREAD

**Issue by bguisard** [titu1994/DenseNet#14]
Hi Somshubra, thanks a lot for this great implementation of FC-DenseNets.

I believe that there may be a connection missing when you use include_top though. You are passing the skip block connection to the last convolutional layer, but I think that the correct approach would be to pass the full output of the last upsampling dense block.

I forked your code and made this change for my last project and got very nice results using a FC-DenseNet56 with sigmoid activation.

Take a look and see if you agree with me, I am happy to send a pull request and make the changes if you want.

Thanks

**Comment by titu1994** [comment]
I think you've solved one of the core bugs. I was facing problems with training it as well and I realise it was my mistake. 

Could you send me a PR ?

**Comment by bguisard** [comment]
Sure! I will get to it later today and send you a PR.

**Comment by titu1994** [comment]
Thanks so very much!
