### ISSUE TITLE
How can I retrain this model ?

### ISSUE THREAD

**Issue by beerboaa** [titu1994/DenseNet#18]
Thank you for this implementation.
I want to know how to use this as transfer learning.
Would you please tell me step by step.

**Comment by titu1994** [comment]
Refer to Keras fine tuning blog post. You can swap out the VGG model there for DenseNet from here, but since I don't have weights for imagenet, you will have to use 'cifar10' instead of 'imagenet'

**Comment by titu1994** [comment]
This is what I meant - https://blog.keras.io/building-powerful-image-classification-models-using-very-little-data.html

**Comment by beerboaa** [comment]
Thank you
