### ISSUE TITLE
Should the input to the include_top ignore the input to the last denseblock?

### ISSUE THREAD

**Issue by jrwin** [titu1994/DenseNet#23]
In the densenet FCN paper, the Diagram of Figure1 show no skip connection from input to output of the last denseblock in the decompression path. 
But the function '__create_fcn_dense_net' use the skip connection like:
line 770 of densenet.py
    `x = Conv2D(nb_classes, (1, 1), activation='linear', padding='same', use_bias=False)(x_up) `

Dose I mis-understand it? Or this operation is an improved one that I miss?

**Comment by titu1994** [comment]
Thats not a skip connection. That is a pixel wise classification layer (where each pixel will be convolved over using a point wise convolution operation to classify that pixel).

**Comment by jrwin** [comment]
I mean the input of the pixel wise classification layer, so call 'x_up',  concatenate the input of its corresponding denseblock. It is different from the paper, where the input to the classification layer should not concatenate the input of the denseblock. And following your code, it should be:
` l = concatenate(concat_list[1:], axis=concat_axis)`
Just like input to others denseblock.  

So I think I may miss something. Could you give me some guidance?

**Comment by titu1994** [comment]
See the last portion. I can't find the mistake, and since it has the exact same number of parameters as the paper (9.4 million), I can't seem to guess where the error is.

![test](https://user-images.githubusercontent.com/3048602/30147532-813a95aa-9364-11e7-8334-ca8bddeb9282.png)

**Comment by jrwin** [comment]
The parameter is similar to the paper's. 
And the diagram of your model-plot seems to be like the attachment. 
The diagram in the Figure 1 of the paper did not have the skip connection in the decompression path.
so I think there may be misunderstanding.

![new microsoft visio drawing](https://user-images.githubusercontent.com/15210486/30155542-ae50b73c-93ef-11e7-8c61-eac55fed0c99.jpg)

**Comment by titu1994** [comment]
I'll look into it. If you can figure out of where to correct it, please submit a PR.
