### ISSUE TITLE
'global_average_pooling2d_1' doesn't exist in 'DenseNet-BC-121-32-no-top.h5' 

### ISSUE THREAD

**Issue by Mudwall** [titu1994/DenseNet#24]
I try "model = DenseNetImageNet121((224,224,3),classes=5, weights='imagenet' ,include_top=False)" and I have downloaded the 'DenseNet-BC-121-32-no-top.h5', so 'model.load_weights( 'DenseNet-BC-121-32-no-top.h5')' is executed.
But the error raised as blowe :
KeyError: "Unable to open object (Object 'global_average_pooling2d_1' doesn't exist)"
Anaconda3,pythin3.6,in Win7.

**Comment by titu1994** [comment]
Oh that's a slight bug. Ill take care of it in some time.

**Comment by titu1994** [comment]
Fixed via 003c562cfd1bc4856cc00c23590705544dd65b74
