### ISSUE TITLE
should input not be concatenated?

### ISSUE THREAD

**Issue by ahundt** [titu1994/DenseNet#27]
Also, looking at several implementations and network diagrams, such as this:
![denseblock](https://github.com/SimJeg/FC-DenseNet/blob/master/DenseBlock.jpg?raw=true)

It appears that in [__denseblock](https://github.com/titu1994/DenseNet/blob/master/densenet.py#L496) needs to be modified a bit because the input is only connected to the output through conv blocks.

```python
x_list = [x]
```
should be:
```python
x_list = []
```

which should mean the relevant instances of `[1:]` in the file can go away. I also think this also means concat_list does not need to be returned.

the same should apply for keras-contrib

**Comment by titu1994** [comment]
It's fine. This is more clear in what it is doing. By stating explicitly that the input is added to the list and not used in concatenate is in line with what the paper wrote, so for clarity I wrote it that way as well. 

Makes no difference in performance.
