### ISSUE TITLE
Question on this repo DenseNet implementation

### ISSUE THREAD

**Issue by thealchemist-x** [titu1994/DenseNet#30]
Hi there, I am interested in using DenseNet for training my dataset to perform object classification and localization. I am wondering if this DenseNet repo allows for transfer learning and also object localization with bounding boxes?

Quite interested in DenseNet as it uses features from all layers due to its concatenations throughout the network!

Thanks guys!

**Comment by jeepkd** [comment]
I'm no expert but you might be looking for an object detection model which implemented DenseNet as a backbone. An interesting one is [DSOD](https://arxiv.org/abs/1708.01241) published by the same author of DenseNet. I find no DSOD implementation on Keras yet, but here is the caffe-based one: https://github.com/szq0214/DSOD

**Comment by thealchemist-x** [comment]
Thanks @jeepkd for your guide :)
