### ISSUE TITLE
Restriction of Activation Layers

### ISSUE THREAD

**Issue by rigelifland** [titu1994/DenseNet#32]
What was the reason behind restricting sigmoid activation to the case where there is only one class? Wouldn't you need to use a sigmoid to do multiclass-multilabel classification?

**Comment by titu1994** [comment]
The original purpose of this algorithm was not multiclass classification. The sigmoid is a special case, used for performing mask regression / object detection.

Of course it can be extended to multiclass as well, but that isn't used as often, and sometimes people can inadvertently use sigmoid as a replacement for Softmax for single class predictions, which it isn't
