### ISSUE TITLE
Failure using Keras' fit_generator attempting to train image classifier

### ISSUE THREAD

**Issue by michaelmurdock** [titu1994/DenseNet#36]
I created a DenseNet model following the instructions in the README.md. I am using Keras with TF for the back-end to train a model (from scratch) to classify 240x240 images into one of 13 classes.

Attached is a simplified script that shows how I set up the model, generators, and optimizer. The code fails when I call the train_generator's fit_generator method. Attached is the output log.

Here are my package versions:

- Python	2.7.5
- cv2	3.3.0
- numpy	1.13.3
- Keras	2.0.8
- Tensorflow	1.2.1
- h5py	2.7.1
- NVCC	release 8.0, V8.0.61
- tensoflow-gpu	1.2.1

[densenet_simplified.txt](https://github.com/titu1994/DenseNet/files/1570420/densenet_simplified.txt)
[densenet_output.txt](https://github.com/titu1994/DenseNet/files/1570421/densenet_output.txt)

Any help in how I might change the configuration to use less memory (if that's what I am doing wrong) would be greatly appreciated.

Thanks,

Michael.

**Comment by titu1994** [comment]
Doesn't the Titan X have 12 GB memory? Also, this is the smallest DenseNet that is in the paper so it shoudn't run out of memory. However, this DenseNet model is used for CIFAR 10/100 models. 

Perhaps try with subsample_initial_block=True, bottleneck=True

**Comment by michaelmurdock** [comment]
I was able to get it working by changing the depth. The "default" is depth=40. I changed it to depth=7, and fit_generator is now working. That is, I don't get the memory failure. It's still on the first epoch but the accuracy is going up, so this looks very promising!
