### ISSUE TITLE
average or max pooling in transition blocks?

### ISSUE THREAD

**Issue by mvoelk** [titu1994/DenseNet#43]
https://github.com/titu1994/DenseNet/blob/c1973213884613bcdf852c4fc67e30b342aba8b9/densenet.py#L530
https://github.com/titu1994/DenseNet/blob/c1973213884613bcdf852c4fc67e30b342aba8b9/densenet_fast.py#L56

**Comment by titu1994** [comment]
Densenet uses Average Pooling for it's transition blocks.

**Comment by mvoelk** [comment]
@titu1994  You're right, but the docstrings in your code are a bit confusing. They say Max Pooling ;)

**Comment by titu1994** [comment]
Ah interesting. You could add a PR to correct them since you caught it, or if you'd like i could patch this

**Comment by mvoelk** [comment]
I leave that to you...
