### ISSUE TITLE
no longer works with newest keras

### ISSUE THREAD

**Issue by jcpeterson** [titu1994/DenseNet#45]
Get `ImportError: cannot import name _obtain_input_shape` with keras 2.2.2 as opposed to 2.2.0

**Comment by titu1994** [comment]
Hmm I gotta fix that. Is it called something else ?

**Comment by jcpeterson** [comment]
Not sure yet. Reverted for now

**Comment by jcpeterson** [comment]
I think you fixed this on contrib. It's keras_application instead of keras.application or something

**Comment by jcpeterson** [comment]
did meant to close this

**Comment by titu1994** [comment]
Fixed via https://github.com/titu1994/DenseNet/commit/70185f37273a361cedf563f90aba8b5e5c039dcc

**Comment by jcpeterson** [comment]
Thanks. Just curious -- did you test this with 2.2.2?

**Comment by titu1994** [comment]
Yes. I have 2.2.2 installed locally and I was able to run the inference script properly v

**Comment by jcpeterson** [comment]
Great
