### ISSUE TITLE
About implementation of __dense_block

### ISSUE THREAD

**Issue by stillwaterman** [titu1994/DenseNet#47]
Hello, I get problem with the function '__dense_block'. I think  this function cannot describe the structure as follow:
![1](https://user-images.githubusercontent.com/20119289/47994207-963a1680-e12c-11e8-9d27-9042cd898729.png)
the code is def __dense_block(x, nb_layers, nb_filter, growth_rate, bottleneck=False, dropout_rate=None, weight_decay=1e-4, grow_nb_filters=True, return_concat_list=False):

    concat_axis = 1 if K.image_data_format() == 'channels_first' else -1

    x_list = [x]

    for i in range(nb_layers):
        cb = __conv_block(x, growth_rate, bottleneck, dropout_rate, weight_decay)
        x_list.append(cb)

        x = concatenate([x, cb], axis=concat_axis)

        if grow_nb_filters:
            nb_filter += growth_rate

    if return_concat_list:
        return x, nb_filter, x_list
    else:
        return x, nb_filter
I think this function did not implement the part of  'the output of the block is the concatenation of the outputs of the 4 layers, and thus contains 4 ∗ k feature maps'. Could you help me to figure it out?

**Comment by stillwaterman** [comment]
sorry, my mistake. I read the author's description about this kind of implementation, he said it's equivalent to the connection pattern described in paper. This is for ease of implementation, one can also keep a set of each layer's feature maps and every time first concate them then do convolution.

**Comment by titu1994** [comment]
It's a kind of overleaved call, and an implementation detail. The model performance the same regardless, and weights loaded for ImageNet are correct. 

Look at the `x = concatenate([x, cb], axis=concat_axis)` line, which performs what the above diagram does. If you read the respective Keras plot or summary, you will find that indeed the feature maps are concatenated at the end.

**Comment by stillwaterman** [comment]
Thanks for your reply, You completely answered my confusion, thanks. :-)
