### ISSUE TITLE
Running Densnet in CPU

### ISSUE THREAD

**Issue by saisivasriram** [titu1994/DenseNet#48]
I ran Densenet.py for mnist dataset, But training got hanged with CPU utilization in 1st epoch itself, Kindly suggest a way to run densenet keras for mnist dataset, and advise of the procedure to run the same in GPU.

**Comment by titu1994** [comment]
DenseNets are very memory exhaustive and time consuming models. It is not possible to train them on CPU for now. On GPU, there is no change to this repo.
