### ISSUE TITLE
Why reshape in fc-densenet in top layer before applying softmax?

### ISSUE THREAD

**Issue by lminer** [titu1994/DenseNet#49]
I was wondering if you had a sense why you need to do a reshape [here](https://github.com/titu1994/DenseNet/blob/master/densenet.py#L781) before applying the softmax.

**Comment by titu1994** [comment]
Because Softmax is only applied to the final dimension, and it should normally be applied only to the channel dimension. 

Nowadays, Softmax supports multidim input and defaults to the last axis, but in earlier versions this was not the case.

**Comment by lminer** [comment]
Thank you! Great explanation.
