### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_file'

### ISSUE THREAD

**Issue by smiler96** [titu1994/DenseNet#50]
```python
Traceback (most recent call last):
  File "D:/GitHub/DenseNet-master/imagenet_inference.py", line 26, in <module>
    print('Predicted:', decode_predictions(preds))
  File "C:\softwares\Anaconda3\envs\Keras\lib\site-packages\keras_applications\imagenet_utils.py", line 224, in decode_predictions
    fpath = keras_utils.get_file(
AttributeError: 'NoneType' object has no attribute 'get_file'
```
kereas 2.2.4, what's the bug of this? How should i do for this bug? Thanks for you!

**Comment by gdbb** [comment]
> ```python
> Traceback (most recent call last):
>   File "D:/GitHub/DenseNet-master/imagenet_inference.py", line 26, in <module>
>     print('Predicted:', decode_predictions(preds))
>   File "C:\softwares\Anaconda3\envs\Keras\lib\site-packages\keras_applications\imagenet_utils.py", line 224, in decode_predictions
>     fpath = keras_utils.get_file(
> AttributeError: 'NoneType' object has no attribute 'get_file'
> ```
> 
> kereas 2.2.4, what's the bug of this? How should i do for this bug? Thanks for you!

In file "imagenet_inference.py", you could replace 
"from densenet import decode_predictions"
with
"from keras.applications.imagenet_utils import decode_predictions".

**Comment by titu1994** [comment]
This is correct fix. Keras keeps changing stuff with every release. I'll patch this in some time.
