### ISSUE TITLE
Mistake in L2 regularization

### ISSUE THREAD

**Issue by benjaminfspector** [titu1994/DenseNet#57]
In the code, the L2 regularization uses the provided weight decay value. Instead, it should use (weight_decay / 2) to cancel out the factor of 2 in the gradient.

Further reading: [https://bbabenko.github.io/weight-decay/](https://bbabenko.github.io/weight-decay/)

**Comment by titu1994** [comment]
This can be done by the user using half the l2 regularization strength.
