### ISSUE TITLE
creat model

### ISSUE THREAD

**Issue by alavi8** [titu1994/DenseNet#59]
I use keras 2.2.4, but when making the model, an error occurs
What should I do?
![Picture1](https://user-images.githubusercontent.com/43337734/61188973-09246580-a69c-11e9-9504-b00fab6d16bd.png)

**Comment by titu1994** [comment]
This is an issue with Tensorflow. Not Keras. Downgrade tensorflow to 1.14.

**Comment by alavi8** [comment]
thank you

**Comment by alavi8** [comment]
I've updated it, but it's still the same error

**Comment by alavi8** [comment]
please guide me
